/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './core/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          50: "var(--ac-primary-50)",
          100: "var(--ac-primary-100)",
          200: "var(--ac-primary-200)",
          300: "var(--ac-primary-300)",
          400: "var(--ac-primary-400)",
          500: "var(--ac-primary-500)",
          600: "var(--ac-primary-600)",
          700: "var(--ac-primary-700)",
          800: "var(--ac-primary-800)",
          900: "var(--ac-primary-900)",
          950: "var(--ac-primary-950)",
          DEFAULT: "var(--ac-primary-500)",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          50: "var(--ac-secondary-50)",
          100: "var(--ac-secondary-100)",
          200: "var(--ac-secondary-200)",
          300: "var(--ac-secondary-300)",
          400: "var(--ac-secondary-400)",
          500: "var(--ac-secondary-500)",
          600: "var(--ac-secondary-600)",
          700: "var(--ac-secondary-700)",
          800: "var(--ac-secondary-800)",
          900: "var(--ac-secondary-900)",
          950: "var(--ac-secondary-950)",
          DEFAULT: "var(--ac-secondary-500)",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          50: "var(--ac-accent-50)",
          100: "var(--ac-accent-100)",
          200: "var(--ac-accent-200)",
          300: "var(--ac-accent-300)",
          400: "var(--ac-accent-400)",
          500: "var(--ac-accent-500)",
          600: "var(--ac-accent-600)",
          700: "var(--ac-accent-700)",
          800: "var(--ac-accent-800)",
          900: "var(--ac-accent-900)",
          950: "var(--ac-accent-950)",
          DEFAULT: "var(--ac-accent-500)",
          foreground: "hsl(var(--accent-foreground))",
        },
        alternate: {
          50: "var(--ac-alternate-50)",
          100: "var(--ac-alternate-100)",
          200: "var(--ac-alternate-200)",
          300: "var(--ac-alternate-300)",
          400: "var(--ac-alternate-400)",
          500: "var(--ac-alternate-500)",
          600: "var(--ac-alternate-600)",
          700: "var(--ac-alternate-700)",
          800: "var(--ac-alternate-800)",
          900: "var(--ac-alternate-900)",
          950: "var(--ac-alternate-950)",
          DEFAULT: "var(--ac-alternate-500)",
        },
        neutral: {
          50: "var(--ac-neutral-50)",
          100: "var(--ac-neutral-100)",
          200: "var(--ac-neutral-200)",
          300: "var(--ac-neutral-300)",
          400: "var(--ac-neutral-400)",
          500: "var(--ac-neutral-500)",
          600: "var(--ac-neutral-600)",
          700: "var(--ac-neutral-700)",
          800: "var(--ac-neutral-800)",
          900: "var(--ac-neutral-900)",
          950: "var(--ac-neutral-950)",
          DEFAULT: "var(--ac-neutral-500)",
        },
        body: {
          50: "var(--ac-body-50)",
          100: "var(--ac-body-100)",
          200: "var(--ac-body-200)",
          300: "var(--ac-body-300)",
          400: "var(--ac-body-400)",
          500: "var(--ac-body-500)",
          600: "var(--ac-body-600)",
          700: "var(--ac-body-700)",
          800: "var(--ac-body-800)",
          900: "var(--ac-body-900)",
          950: "var(--ac-body-950)",
          DEFAULT: "var(--ac-body-500)",
        },
        alert: {
          50: "var(--ac-alert-50)",
          100: "var(--ac-alert-100)",
          200: "var(--ac-alert-200)",
          300: "var(--ac-alert-300)",
          400: "var(--ac-alert-400)",
          500: "var(--ac-alert-500)",
          600: "var(--ac-alert-600)",
          700: "var(--ac-alert-700)",
          800: "var(--ac-alert-800)",
          900: "var(--ac-alert-900)",
          950: "var(--ac-alert-950)",
          DEFAULT: "var(--ac-alert-500)",
        },
        success: {
          50: "var(--ac-success-50)",
          100: "var(--ac-success-100)",
          200: "var(--ac-success-200)",
          300: "var(--ac-success-300)",
          400: "var(--ac-success-400)",
          500: "var(--ac-success-500)",
          600: "var(--ac-success-600)",
          700: "var(--ac-success-700)",
          800: "var(--ac-success-800)",
          900: "var(--ac-success-900)",
          950: "var(--ac-success-950)",
          DEFAULT: "var(--ac-success-500)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "slide-from-left": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-to-left": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-100%)" },
        },
        "slide-from-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-to-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(100%)" },
        },
        "slide-from-top": {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(0)" },
        },
        "slide-to-top": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(-100%)" },
        },
        "slide-from-bottom": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
        "slide-to-bottom": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(100%)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-out": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "scale-out": {
          "0%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(0.95)", opacity: "0" },
        },
        "spin": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "ping": {
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
        "bounce": {
          "0%, 100%": { transform: "translateY(-25%)", animationTimingFunction: "cubic-bezier(0.8, 0, 1, 1)" },
          "50%": { transform: "translateY(0)", animationTimingFunction: "cubic-bezier(0, 0, 0.2, 1)" },
        },
        "pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: ".5" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-4px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(4px)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-from-left": "slide-from-left 0.3s ease-out",
        "slide-to-left": "slide-to-left 0.3s ease-out",
        "slide-from-right": "slide-from-right 0.3s ease-out",
        "slide-to-right": "slide-to-right 0.3s ease-out",
        "slide-from-top": "slide-from-top 0.3s ease-out",
        "slide-to-top": "slide-to-top 0.3s ease-out",
        "slide-from-bottom": "slide-from-bottom 0.3s ease-out",
        "slide-to-bottom": "slide-to-bottom 0.3s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "fade-out": "fade-out 0.2s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "scale-out": "scale-out 0.2s ease-out",
        "spin": "spin 1s linear infinite",
        "ping": "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
        "bounce": "bounce 1s infinite",
        "pulse": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "shake": "shake 0.8s cubic-bezier(.36,.07,.19,.97) both",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
} 